language: go
go:
  - "1.11"
  - "1.13"
  - "1.14"
  - master

install:
  - go get -d -v .

script:
  - go test
  - go build -v ./
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run -v

