language: go
go:
  - 1.11.x
  - 1.13.x
  - 1.14.x
  - master

install:
  - go get -d -v .

script:
  - go test
  - go build -v ./
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint && golangci-lint run -v

